### ISSUE TITLE
Is the "sealed" really necessary?

### ISSUE THREAD

**Issue by Leh2** [MarcosMeli/FileHelpers#35]
I would love to extend attributes like `FieldAlignAttribute` to match my current requirements and to avoid repeating `[FieldAlign(AlignMode.Right, '0')]`.

I could imagine the reason for using sealed is about performance, but are there really any significant gains, to justify the removal of extensibility?

If there are other reasons I haven't thought of, please enlighten me :)

**Comment by MarcosMeli** [comment]
Hi there

All attributes are marked as sealed because the library knows how to work with them, if you inherit from it and add extra info it don't get used

But thinking in your scenario, is completely right to create a FieldAlignRightWithZero() and call the constructor of the FieldAlignAtrribute

Cheers
