### ISSUE TITLE
What is new in 3.x?

### ISSUE THREAD

**Issue by waynebrantley** [MarcosMeli/FileHelpers#36]
As a long time user of 2.x - is there a 'conversion' document for 
-  What has been removed/changed
-  Migration guide
-  New features, etc?

**Comment by mcavigelli** [comment]
Hello Wayne

I have looked into the file Doc/Include/history.html and found the following:

## Main Changes

* The core code of the library was refactored to make easier to extend it
* Better performance, mostly for FixedLenght records
* The error messages have been made more meaningful. In all exceptions you get; the FieldName, ColumnNumber, LineNumber, etc.
* Docs rewritten thanks to the work of Ken Foskey
* CHANGED: Removed support for .NET Compact Framework
* CHANGED: Better caching of internal classes
* NEW: Full .NET 2.0, 4.0 & 4.5 support
* NEW: FieldOrder: a new attribute to override the default order of fields
* NEW: FieldNotEmpty : Indicates whether the target field needs to be populated with a non-empty value.
* NEW: Partial support to use Autoproperties
* NEW: Async Methods returns IDisposable to allow using() statements that autoclose files on ends or exception
* NEW: ReadFileAsList: new methods to directly get a List<T> instead of an array
* NEW: Events for the Async engines
* NEW: The events args now have TotalBytes and CurrentBytes to allow you show progress while reading or writting
* NEW: FieldIndexers you can now get the values in the AsyncEngine like in the DataReader of ADO.NET =)
     You can access them via index or fieldName (at the moment case sensitive)
     This also completes the RunTime records support
* NEW: FormatDetector: A class designed to discover the format of delimited and flat files based on sample files. It is integrated with the wizzard
* NEW: Better Delited validations to make sure that the file contains the right number of fields
* NEW: FieldValueDiscarted: a new attribute to allow the value of a particular field to be read but not stored in the record class (this was a very requested feature)			
* NEW: BigFileSorter: if you need to sort big files, you can use this feature that implements External Sorting 			

## Minor changes

* ADD: UpdateLinks properties, allow to specify how the library must handle Workbook links (thanks to Stefan Schälle)
* Some new examples
* FIX: A little problem with the quoted fields in the wizard
* More documentation has been added to the Library source code.
    It is now even easier to get involved in development!
* Lots of minor documentation updates

**Comment by mcavigelli** [comment]
Hello Wayne

Did that answer your question? If so, can we close this issue?

Matthias

**Comment by waynebrantley** [comment]
Yeah, that is good information.  I want to upgrade and if this project is 'going again', I have several enhancements I would like to contribute...as well as change some 'internal sealed' classes to just public, etc.   When is it going to be out of alpha/pre-release?

**Comment by mcavigelli** [comment]
Hello Wayne
I don't know what is missing for a stable release.
Have you tried the beta as described in #31?

@MarcosMeli, could you please hang in and explain what is missing?

Matthias

**Comment by MarcosMeli** [comment]
Hi there, we are active working in 3.1 version

We are working hard in the new HomePage www.filehelpers.net

Also in the new issue tracking moved here to GitHub and using waffle
https://waffle.io/MarcosMeli/FileHelpers?milestone=3.1%20Release

I will close this issue because it will continue in #75 

Wayne will be great if you join us in the process to release 3.1 and suggest changes to for 4.0 version

Already in NuGet is the beta version of the library
