### ISSUE TITLE
Need to use a "shared template" for both fixed length and delimited record

### ISSUE THREAD

**Issue by cristianoalvesdasilva** [MarcosMeli/FileHelpers#94]
Hey! Probably that's not the right place to post a question, so my apologies in advance :)

Here it is my question: I got a situation where I need to write a file using either fixed length OR delimited record format depending on a certain condition. Is there a way to re-use the same template? I know if I use both FixedLenghtRecord and DelimitedRecord attributes on the same class/template a BadUsageException will be thrown by the FileHelperEngine.

Thanks!
Cris

**Comment by MarcosMeli** [comment]
Hi Cris

Thats not posible with the current version of the library :( because of the internals one type can have only a Record Attribute. You can write multiple delimited files changing delimiter, but you can't use the same for Fixed Length

The best suggestion I have is to create an Interface with all the fields, later create two classes that implements the interface (one with de FixedLengthRecord attribute and other with the DelimitedRecord.

In your code, only use the interface to fill the record values

Hope that helps
Marcos
